*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 14.03.2019 at 07:16:13
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVOPS_T001KML...................................*
TABLES: ZVOPS_T001KML, *ZVOPS_T001KML. "view work areas
CONTROLS: TCTRL_ZVOPS_T001KML
TYPE TABLEVIEW USING SCREEN '9502'.
DATA: BEGIN OF STATUS_ZVOPS_T001KML. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_T001KML.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_T001KML_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_T001KML.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_T001KML_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_T001KML_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_T001KML.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_T001KML_TOTAL.

*...processing: ZVOPS_TCKM2.....................................*
TABLES: ZVOPS_TCKM2, *ZVOPS_TCKM2. "view work areas
CONTROLS: TCTRL_ZVOPS_TCKM2
TYPE TABLEVIEW USING SCREEN '9501'.
DATA: BEGIN OF STATUS_ZVOPS_TCKM2. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TCKM2.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TCKM2_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TCKM2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TCKM2_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TCKM2_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TCKM2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TCKM2_TOTAL.

*...processing: ZVOPS_TKA3A.....................................*
TABLES: ZVOPS_TKA3A, *ZVOPS_TKA3A. "view work areas
CONTROLS: TCTRL_ZVOPS_TKA3A
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZVOPS_TKA3A. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TKA3A.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TKA3A_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TKA3A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TKA3A_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TKA3A_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TKA3A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TKA3A_TOTAL.

*...processing: ZVOPS_TKA3P.....................................*
TABLES: ZVOPS_TKA3P, *ZVOPS_TKA3P. "view work areas
CONTROLS: TCTRL_ZVOPS_TKA3P
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZVOPS_TKA3P. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TKA3P.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TKA3P_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TKA3P.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TKA3P_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TKA3P_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TKA3P.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TKA3P_TOTAL.

*...processing: ZVOPS_TVKWZ_ASSI................................*
TABLES: ZVOPS_TVKWZ_ASSI, *ZVOPS_TVKWZ_ASSI. "view work areas
CONTROLS: TCTRL_ZVOPS_TVKWZ_ASSI
TYPE TABLEVIEW USING SCREEN '9503'.
DATA: BEGIN OF STATUS_ZVOPS_TVKWZ_ASSI. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TVKWZ_ASSI.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TVKWZ_ASSI_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TVKWZ_ASSI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TVKWZ_ASSI_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TVKWZ_ASSI_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TVKWZ_ASSI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TVKWZ_ASSI_TOTAL.

*...processing: ZVOPS_TVSTZ_STOR................................*
TABLES: ZVOPS_TVSTZ_STOR, *ZVOPS_TVSTZ_STOR. "view work areas
CONTROLS: TCTRL_ZVOPS_TVSTZ_STOR
TYPE TABLEVIEW USING SCREEN '9506'.
DATA: BEGIN OF STATUS_ZVOPS_TVSTZ_STOR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TVSTZ_STOR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TVSTZ_STOR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TVSTZ_STOR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TVSTZ_STOR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TVSTZ_STOR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TVSTZ_STOR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TVSTZ_STOR_TOTAL.

*...processing: ZVOPS_TWLAD.....................................*
TABLES: ZVOPS_TWLAD, *ZVOPS_TWLAD. "view work areas
CONTROLS: TCTRL_ZVOPS_TWLAD
TYPE TABLEVIEW USING SCREEN '9504'.
DATA: BEGIN OF STATUS_ZVOPS_TWLAD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVOPS_TWLAD.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVOPS_TWLAD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TWLAD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TWLAD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVOPS_TWLAD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVOPS_TWLAD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVOPS_TWLAD_TOTAL.

*.........table declarations:.................................*
TABLES: T001                           .
TABLES: T001K                          .
TABLES: T001W                          .
TABLES: TASSIGN_SD_VKORG               .
TABLES: TCKM2                          .
TABLES: TKA3A                          .
TABLES: TKA3P                          .
TABLES: TVKO                           .
TABLES: TVKOT                          .
TABLES: TVKOV                          .
TABLES: TVKWZ                          .
TABLES: TVSTZ_STORLOC                  .
TABLES: TVTW                           .
TABLES: TVTWT                          .
TABLES: TWLAD                          .
